[package]
name = "color"
version = "0.1.0"
edition = "2024"

[dependencies]
arc = { workspace = true }
bitset = { workspace = true }
rand = "0.10.1"
rustc-hash = "2.1.2"
csv = "1.4.0"
paste = { version = "1.0.15" }
clap = { version = "4.6.1", features = ["derive"] }

[[bin]]
name = "color-ratio"
path = "bin/ratio.rs"

[[bin]]
name = "color-bench"
path = "bin/bench.rs"

[[bin]]
name = "color-solve"
path = "bin/solve.rs"

[[bin]]
name = "color-stage"
path = "bin/stage.rs"